# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifiers',
            fields=[
                ('classifier_id', models.AutoField(primary_key=True, serialize=False)),
                ('classifier_name', models.CharField(max_length=30)),
            ],
        ),
    ]
