# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_classifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictTypes',
            fields=[
                ('type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'conf_types',
                'managed': False,
            },
        ),
    ]
